### PR TITLE
random_state

### PR DESCRIPTION
**Pull request by amandaher**
Solving issue #77.

### CODE REVIEW

**Comment by amandaher** [comment]
@pablomm I am following the changes you suggested in this pull request, however, I do not understand why this should solve the failing of the tests.

**Comment by pablomm** [comment]
> @pablomm I am following the changes you suggested in this pull request, however, I do not understand why this should solve the failing of the tests.

As @vnmabus says in #77, `MinCovDet` uses some type of random estimation of the variance, and the result of the magnitude shape plot won't have to be the same in all the executions, which is why tests sometimes fail. 

Setting the random state the result of the test will always be the same.

**Comment by amandaher** [comment]
I understand that, however, since the error is the below one:
`(mismatch 8.57142857142857%)
x: array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1]) 
y: array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1])`,
it seems to me a problem related to the precision of the comparison rather than to the randomness. 
Nevertheless,  giving the  possibility of specifying the random state is an upgrade for the code.

**Comment by pablomm** [comment]
But the last elements of the arrays are different, it is not for the tolerance.
```
x: array([..., 1, 0, 1, 1, 1]) 
y: array([..., 0, 0, 0, 0, 1])
```

**Pull request merged**
